version: '3.8'

services:
    postgres:
        image: postgres:15-alpine
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U user']
            interval: 10s
            timeout: 5s
            retries: 5

    backend:
        build:
            context: ./app
            dockerfile: Dockerfile
        environment:
            NODE_ENV: production
            DATABASE_URL_APP: 'postgresql://user:password@postgres:5432/postgres'
            APP_CORS: 'http://localhost:5173'
        ports:
            - '3000:3000'
        depends_on:
            postgres:
                condition: service_healthy

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                VITE_API_URL: 'http://localhost:3000'
        environment:
            - VITE_API_URL=http://localhost:3000 # Adjust this URL as needed
        ports:
            - '5173:5173'
        depends_on:
            - backend

volumes:
    postgres_data:
